"""
Rust parity test — cross-validates Python collateral against the pre-computed
values in apps/android-demo/app/src/main/assets/demo_market.json.

The JSON was generated by the Rust `export_demo_payload` binary and contains
ground-truth collateral figures for each demo preset.  This test verifies
that our Python golden-section minimizer matches to within 1 basis point
(0.01%) relative error.

Run:  pytest simulations/pdamm/tests/test_rust_parity.py -v
"""

from __future__ import annotations

import json
import math
import os
import pytest

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../../.."))

from pdamm.amm.gaussian_mixture import (
    GaussianMixtureAMM,
    GaussianMixtureParams,
    compute_collateral,
)


# ---------------------------------------------------------------------------
# Load ground-truth data
# ---------------------------------------------------------------------------

_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../.."))
_DEMO_JSON = os.path.join(
    _REPO_ROOT,
    "apps/android-demo/app/src/main/assets/demo_market.json",
)


def _load_presets() -> list[dict]:
    with open(_DEMO_JSON) as fh:
        data = json.load(fh)
    return data["presets"]


def _load_market_config() -> dict:
    with open(_DEMO_JSON) as fh:
        data = json.load(fh)
    return data["market"]


# ---------------------------------------------------------------------------
# Reconstruct AMM state from the JSON market config
# ---------------------------------------------------------------------------

def _build_amm_from_json() -> GaussianMixtureAMM:
    """
    Reconstruct the AMM from the JSON market stanza.

    k is not stored in the JSON.  The exact value is hard-coded from
    crates/normal-v1-sdk/src/lib.rs::seeded_demo_market():
        initial_k: Fixed::from_f64(21.05026039569057)
    It equals b/10 * sqrt(sigma * sqrt(π)) = 5 * sqrt(10 * sqrt(π)).
    """
    market = _load_market_config()

    mu = float(market["current_mu_display"])
    sigma = float(market["current_sigma_display"])
    b = float(market["backing_display"])

    # Exact Rust k from seeded_demo_market in crates/normal-v1-sdk/src/lib.rs
    k = 5.0 * math.sqrt(10.0 * math.sqrt(math.pi))

    params = GaussianMixtureParams.single(mu=mu, sigma=sigma)
    # Bypass the post-init solvency check since we trust the Rust-computed k/b
    amm = GaussianMixtureAMM.__new__(GaussianMixtureAMM)
    amm.b = b
    amm.k = k
    amm.params = params
    amm.taker_fee_bps = int(market.get("taker_fee_bps", 100))
    amm.min_taker_fee = float(market.get("min_taker_fee", 0.001))
    amm.max_collateral_per_trade = float(market.get("max_collateral_per_trade", 50.0))
    amm.state_version = 0
    amm.trades = []
    amm.cash = 0.0
    amm.fees_accrued = 0.0
    return amm


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

RELATIVE_TOLERANCE = 1e-4  # 1 basis point


@pytest.fixture(scope="module")
def demo_presets() -> list[dict]:
    if not os.path.exists(_DEMO_JSON):
        pytest.skip(f"demo_market.json not found at {_DEMO_JSON}")
    return _load_presets()


@pytest.fixture(scope="module")
def base_amm() -> GaussianMixtureAMM:
    if not os.path.exists(_DEMO_JSON):
        pytest.skip(f"demo_market.json not found at {_DEMO_JSON}")
    return _build_amm_from_json()


class TestCollateralParity:
    def test_presets_present(self, demo_presets):
        assert len(demo_presets) > 0, "no presets found in demo_market.json"

    @pytest.mark.parametrize("preset_index", range(0, 5))
    def test_collateral_matches_rust(self, demo_presets, base_amm, preset_index):
        if preset_index >= len(demo_presets):
            pytest.skip(f"preset {preset_index} not in fixture")

        preset = demo_presets[preset_index]
        rust_collateral = float(preset["collateral_required_display"])

        target_mu = float(preset["target_mu_display"])
        target_sigma = float(preset["target_sigma_display"])
        new_params = GaussianMixtureParams.single(mu=target_mu, sigma=target_sigma)

        python_collateral = compute_collateral(
            base_amm.params,
            new_params,
            base_amm.k,
            coarse_samples=1024,
        )

        if rust_collateral < 1e-9:
            assert python_collateral < 1e-6, (
                f"preset {preset['id']}: expected ~0 collateral, got {python_collateral:.6f}"
            )
        else:
            rel_err = abs(python_collateral - rust_collateral) / rust_collateral
            assert rel_err < RELATIVE_TOLERANCE, (
                f"preset {preset['id']}: python={python_collateral:.6f}, "
                f"rust={rust_collateral:.6f}, rel_err={rel_err:.2e}"
            )


class TestCurvePointParity:
    """
    Verify that Python f(x) values match the Rust-computed curve_points for the
    first preset, within floating-point round-trip tolerance.
    """

    def test_curve_points_match(self, demo_presets, base_amm):
        preset = demo_presets[0]
        target_mu = float(preset["target_mu_display"])
        target_sigma = float(preset["target_sigma_display"])
        new_params = GaussianMixtureParams.single(mu=target_mu, sigma=target_sigma)

        from pdamm.amm.gaussian_mixture import position_value

        errors = []
        for pt in preset["curve_points"]:
            x = float(pt["x"])
            rust_current = float(pt["current"])
            rust_proposed = float(pt["proposed"])

            py_current = position_value(x, base_amm.params, base_amm.k)
            py_proposed = position_value(x, new_params, base_amm.k)

            err_current = abs(py_current - rust_current)
            err_proposed = abs(py_proposed - rust_proposed)
            errors.append(max(err_current, err_proposed))

        max_err = max(errors)
        assert max_err < 1e-4, (
            f"curve point mismatch: max absolute error = {max_err:.2e}"
        )
