import type { DemoPayload } from "./types";

function regimeHistory(center: number, count = 32): import("./types").DemoRegimeHistoryPoint[] {
  return Array.from({ length: count }, (_, i) => {
    const t = i / (count - 1);
    const noise = Math.sin(t * 5 + center) * center * 0.04 + (((center * 31 + i * 17) % 100) / 100 - 0.5) * center * 0.025;
    return { slot: 300_000_000 + i * 50_000, level_display: (center + noise).toFixed(3) };
  });
}

function perpHistory(center: number, count = 24): import("./types").DemoPerpFundingPoint[] {
  return Array.from({ length: count }, (_, i) => {
    const noise = Math.sin(i * 0.7) * center * 0.015;
    const mu = center + noise;
    return {
      slot: 304_000_000 + i * 100_000,
      amm_mu_display: mu.toFixed(4),
      anchor_mu_display: (center + Math.sin(i * 0.4) * center * 0.008).toFixed(4),
      kl_display: (0.12 + Math.sin(i * 0.9) * 0.03).toFixed(6),
      funding_rate_display: ((Math.sin(i * 0.7) * 0.0015)).toFixed(6),
    };
  });
}

function perpCurve(mu: number, sigma: number, points = 40): import("./types").DemoPerpCurvePoint[] {
  const lo = mu - sigma * 3.5;
  const hi = mu + sigma * 3.5;
  return Array.from({ length: points }, (_, i) => {
    const x = lo + (hi - lo) * (i / (points - 1));
    const z = (x - mu) / sigma;
    const amm = Math.exp(-0.5 * z * z) / (sigma * Math.sqrt(2 * Math.PI));
    const anchorZ = (x - (mu + sigma * 0.12)) / (sigma * 1.08);
    const anchor = Math.exp(-0.5 * anchorZ * anchorZ) / (sigma * 1.08 * Math.sqrt(2 * Math.PI));
    const edge = amm - anchor;
    return { x, amm, anchor, edge };
  });
}

export const STATIC_PAYLOAD: DemoPayload = {
  market: {
    title: "ETH/USD · Pyth oracle · Jun 30, 2026",
    status: "Active · devnet",
    market_id_hex: "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2",
    state_version: 3,
    current_mu_display: "3240.000000000",
    current_sigma_display: "390.000000000",
    k_display: "1000.000000000",
    backing_display: "5200.000000000",
    taker_fee_bps: 30,
    min_taker_fee_display: "0.050000000",
    maker_fees_earned_display: "14.320000000",
    maker_deposit_display: "500.000000000",
    total_trades: 312,
    max_open_trades: 1000,
    expiry_slot: 315_000_000,
    demo_quote_slot: 305_200_000,
    demo_quote_expiry_slot: 305_210_000,
    coarse_samples: 64,
    refine_samples: 32,
    subtitle: "Pyth ETH/USD · on-chain devnet settlement",
    category_label: "Crypto",
    unit_label: "$",
    resolves_at_label: "Jun 30, 2026",
    volume_usd: 148_000,
    bettor_count: 312,
    resolution_source_label: "Pyth ETH/USD oracle",
    resolution_rule_text: "Pyth ETH/USD price feed at expiry slot on Solana devnet. Outcome scaled to display units.",
    source_badge: "DEVNET",
    featured_live: false,
  },

  presets: [],
  quote_grid: [],

  regime_indexes: [
    {
      id: "crbull",
      symbol: "CRBULL",
      title: "Crypto Bull Cycle Index",
      thesis: "Tracks the probability that crypto markets are in a sustained bull phase — long exposure to BTC dominance, ETH momentum, and on-chain activity.",
      status: "active",
      level_display: "68.500",
      previous_level_display: "65.200",
      change_display: "+3.300",
      rebalance_slot: 300_000_000,
      next_rebalance_slot: 306_000_000,
      quote_expiry_slot: 305_210_000,
      history: regimeHistory(68.5),
      constituents: [
        {
          id: "btc-dom",
          label: "BTC Dominance > 52%",
          side: "Long",
          weight_bps: 3000,
          probability_display: "0.720",
          previous_probability_display: "0.690",
          level_contribution_display: "21.600",
          signed_pressure_display: "+0.030",
          status: "active",
          expiry_slot: 310_000_000,
        },
        {
          id: "eth-mom",
          label: "ETH 30d Momentum > 0",
          side: "Long",
          weight_bps: 2500,
          probability_display: "0.640",
          previous_probability_display: "0.620",
          level_contribution_display: "16.000",
          signed_pressure_display: "+0.020",
          status: "active",
          expiry_slot: 310_000_000,
        },
        {
          id: "onchain-vol",
          label: "DEX Volume > $10B/week",
          side: "Long",
          weight_bps: 2000,
          probability_display: "0.810",
          previous_probability_display: "0.790",
          level_contribution_display: "16.200",
          signed_pressure_display: "+0.020",
          status: "active",
          expiry_slot: 310_000_000,
        },
        {
          id: "fear-greed",
          label: "Fear & Greed Index > 60",
          side: "Long",
          weight_bps: 1500,
          probability_display: "0.590",
          previous_probability_display: "0.540",
          level_contribution_display: "8.850",
          signed_pressure_display: "+0.050",
          status: "active",
          expiry_slot: 310_000_000,
        },
        {
          id: "stablecoin-flow",
          label: "Stablecoin Inflows > $2B/week",
          side: "Long",
          weight_bps: 1000,
          probability_display: "0.660",
          previous_probability_display: "0.650",
          level_contribution_display: "6.600",
          signed_pressure_display: "+0.010",
          status: "active",
          expiry_slot: 310_000_000,
        },
      ],
      long_quote: {
        side: "Long",
        size_display: "1.000",
        entry_level_display: "68.500",
        token_price_display: "0.685",
        collateral_required_display: "6.850",
        fee_paid_display: "0.021",
        total_debit_display: "6.871",
        memo_payload: "crbull_long_v1",
      },
      short_quote: {
        side: "Short",
        size_display: "1.000",
        entry_level_display: "68.500",
        token_price_display: "0.315",
        collateral_required_display: "3.150",
        fee_paid_display: "0.010",
        total_debit_display: "3.160",
        memo_payload: "crbull_short_v1",
      },
    },
    {
      id: "ratec",
      symbol: "RATEC",
      title: "Rate Cut Cascade Index",
      thesis: "Tracks the probability of a sustained Fed rate-cutting cycle — long exposure to rate cut expectations, credit spread tightening, and housing starts recovery.",
      status: "active",
      level_display: "42.100",
      previous_level_display: "44.800",
      change_display: "-2.700",
      rebalance_slot: 300_000_000,
      next_rebalance_slot: 306_000_000,
      quote_expiry_slot: 305_210_000,
      history: regimeHistory(42.1),
      constituents: [
        {
          id: "fed-cut-prob",
          label: "Fed cut ≥50bps by Dec 2026",
          side: "Long",
          weight_bps: 3500,
          probability_display: "0.380",
          previous_probability_display: "0.420",
          level_contribution_display: "13.300",
          signed_pressure_display: "-0.040",
          status: "active",
          expiry_slot: 312_000_000,
        },
        {
          id: "credit-spread",
          label: "IG Spread < 90bps",
          side: "Long",
          weight_bps: 2500,
          probability_display: "0.450",
          previous_probability_display: "0.460",
          level_contribution_display: "11.250",
          signed_pressure_display: "-0.010",
          status: "active",
          expiry_slot: 312_000_000,
        },
        {
          id: "housing-starts",
          label: "Housing Starts > 1.4M annualized",
          side: "Long",
          weight_bps: 2000,
          probability_display: "0.420",
          previous_probability_display: "0.430",
          level_contribution_display: "8.400",
          signed_pressure_display: "-0.010",
          status: "active",
          expiry_slot: 312_000_000,
        },
        {
          id: "core-pce",
          label: "Core PCE < 2.5% by Q3",
          side: "Long",
          weight_bps: 2000,
          probability_display: "0.470",
          previous_probability_display: "0.490",
          level_contribution_display: "9.400",
          signed_pressure_display: "-0.020",
          status: "active",
          expiry_slot: 312_000_000,
        },
      ],
      long_quote: {
        side: "Long",
        size_display: "1.000",
        entry_level_display: "42.100",
        token_price_display: "0.421",
        collateral_required_display: "4.210",
        fee_paid_display: "0.013",
        total_debit_display: "4.223",
        memo_payload: "ratec_long_v1",
      },
      short_quote: {
        side: "Short",
        size_display: "1.000",
        entry_level_display: "42.100",
        token_price_display: "0.579",
        collateral_required_display: "5.790",
        fee_paid_display: "0.018",
        total_debit_display: "5.808",
        memo_payload: "ratec_short_v1",
      },
    },
  ],

  perps: {
    symbol: "SOL-USD",
    title: "SOL/USD Perpetual",
    status: "active",
    slot: 305_150_000,
    next_funding_slot: 305_200_000,
    funding_interval: 50_000,
    mark_price_display: "158.4200",
    anchor_mu_display: "156.9000",
    anchor_sigma_display: "18.0000",
    amm_mu_display: "158.4200",
    amm_sigma_display: "17.5000",
    kl_display: "0.124000",
    spot_funding_rate_display: "+0.000820",
    vault_cash_display: "820.0000",
    lp_nav_display: "850.4000",
    available_lp_cash_display: "612.0000",
    open_positions: 14,
    total_lp_shares_display: "1000.0000",
    curve_points: perpCurve(158.42, 17.5),
    funding_path: perpHistory(158.42),
    long_quote: {
      side: "Long",
      target_mu_display: "162.0000",
      target_sigma_display: "15.0000",
      collateral_required_display: "18.4000",
      fee_paid_display: "0.0550",
      total_debit_display: "18.4550",
      estimated_funding_display: "+0.0820",
      close_mark_display: "158.4200",
      memo_payload: "sol_long_v1",
    },
    short_quote: {
      side: "Short",
      target_mu_display: "155.0000",
      target_sigma_display: "15.0000",
      collateral_required_display: "16.2000",
      fee_paid_display: "0.0490",
      total_debit_display: "16.2490",
      estimated_funding_display: "-0.0820",
      close_mark_display: "158.4200",
      memo_payload: "sol_short_v1",
    },
    positions: [
      {
        id: "pos-001",
        side: "Long",
        entry_mu_display: "152.3000",
        collateral_display: "22.5000",
        funding_paid_display: "0.1840",
        funding_received_display: "0.0000",
        mark_payout_display: "156.8000",
        status: "open",
      },
      {
        id: "pos-002",
        side: "Short",
        entry_mu_display: "164.8000",
        collateral_display: "18.0000",
        funding_paid_display: "0.0000",
        funding_received_display: "0.2460",
        mark_payout_display: "158.4200",
        status: "open",
      },
    ],
  },
};
